title: <%= name %>
publicURL: http://localhost:3003/
datamanagerID: <%= dataManagerID %>
shortID: <%= shortID %>
env: <%= env %>
useSDK: true
locale: de # for date/time formatting
timezone: Europe/Berlin # for date/time formatting
analyticsID:
dynamicTemplates: {}
disableCrawling: true
disableTLS: false
disableTemplateCache: true
memoryCacheTtl: 3600 # in seconds => 1 hour
dmCache:
  cacheSize: 1000
  timeToLive: undefined
  appendSource: true
port: 7777
amqp:
  user: render
  password: render
logger:
  console:
    active: true
  cloudwatch:
    active: true
